# ansible-playbook.yml 
---
- name: Deploy to Kubernetes master
  hosts: kubernetes_master
  tasks:
    - name: Copy manifest to Kubernetes master
      ansible.builtin.copy:
        src: "/home/devopsadmin/workspace/IInsurance_deploy_Ansiblecontroller/kubernetesdeploy.yaml"
        dest: "/home/devopsadmin/kubernetesdeploy.yaml"
        # Optional: Add validation if needed
        # validate: 'kubectl apply -f %s --dry-run=client'

    - name: Apply the manifest
      ansible.builtin.shell:
        cmd: "kubectl apply -f /home/devopsadmin/kubernetesdeploy.yaml"
      register: kubectl_output

    - name: Print deployment result
      ansible.builtin.debug:
        var: kubectl_output.stdout
