---
- name: Install Java, Maven, Git, and Docker
  hosts: jenkins_slave
  become: yes
  tasks:
    - name: Install base packages
      apt:
        name:
          - openjdk-11-jdk
          - maven
          - git
        update_cache: yes

    - name: Add Docker repository prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
